// flow-typed signature: b6ceb82a15b7fca5412ee0a211cc605f
// flow-typed version: <<STUB>>/draftjs-to-html_v^0.8.4/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draftjs-to-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draftjs-to-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draftjs-to-html/lib/draftjs-to-html' {
  declare module.exports: any;
}

declare module 'draftjs-to-html/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draftjs-to-html/lib/draftjs-to-html.js' {
  declare module.exports: $Exports<'draftjs-to-html/lib/draftjs-to-html'>;
}
declare module 'draftjs-to-html/rollup.config.js' {
  declare module.exports: $Exports<'draftjs-to-html/rollup.config'>;
}
