// flow-typed signature: 40703b1e607150c372e0bdd5f3cd1000
// flow-typed version: <<STUB>>/html-to-draftjs_v^1.4.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-to-draftjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-to-draftjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-to-draftjs/dist/html-to-draftjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-to-draftjs/dist/html-to-draftjs.js' {
  declare module.exports: $Exports<'html-to-draftjs/dist/html-to-draftjs'>;
}
