// flow-typed signature: e6386910a8aab133ecc89f099abcba94
// flow-typed version: <<STUB>>/material-ui-pickers_v^2.0.5/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui-pickers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui-pickers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui-pickers/_helpers/date-utils' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_helpers/text-field-helper' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_helpers/time-utils' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/BasePicker' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/DateTextField' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/icons/ArrowLeftIcon' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/icons/ArrowRightIcon' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/icons/DateRangeIcon' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/icons/KeyboardIcon' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/icons/TimeIcon' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/MaskedInput' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/ModalDialog' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/PickerToolbar' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/ToolbarButton' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/WithUtils' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/constants/ClockType' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/constants/DateTimePickerView' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/constants/dimensions' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/constants/prop-types' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/components/Calendar' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/components/CalendarHeader' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/components/Day' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/components/DayWrapper' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/components/SlideTransition' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/components/Year' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/components/YearSelection' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/DatePicker' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/DatePickerInline' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/DatePickerModal' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/index' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DateTimePicker/components/DateTimePickerHeader' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DateTimePicker/components/DateTimePickerTabs' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DateTimePicker/components/DateTimePickerView' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DateTimePicker/DateTimePicker' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DateTimePicker/DateTimePickerInline' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DateTimePicker/DateTimePickerModal' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DateTimePicker/index' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/dist/material-ui-pickers.cjs' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/dist/material-ui-pickers.esm' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/dist/material-ui-pickers.umd' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/dist/material-ui-pickers.umd.min' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/MuiPickersUtilsProvider' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/components/Clock' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/components/ClockNumber' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/components/ClockNumbers' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/components/ClockPointer' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/components/TimePickerView' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/index' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/TimePicker' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/TimePickerInline' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/TimePickerModal' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/typings/date' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/typings/extendMui' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/typings/overrides' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/wrappers/ExtendWrapper' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/wrappers/InlineWrapper' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/wrappers/ModalWrapper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui-pickers/_helpers/date-utils.js' {
  declare module.exports: $Exports<'material-ui-pickers/_helpers/date-utils'>;
}
declare module 'material-ui-pickers/_helpers/text-field-helper.js' {
  declare module.exports: $Exports<'material-ui-pickers/_helpers/text-field-helper'>;
}
declare module 'material-ui-pickers/_helpers/time-utils.js' {
  declare module.exports: $Exports<'material-ui-pickers/_helpers/time-utils'>;
}
declare module 'material-ui-pickers/_shared/BasePicker.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/BasePicker'>;
}
declare module 'material-ui-pickers/_shared/DateTextField.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/DateTextField'>;
}
declare module 'material-ui-pickers/_shared/icons/ArrowLeftIcon.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/icons/ArrowLeftIcon'>;
}
declare module 'material-ui-pickers/_shared/icons/ArrowRightIcon.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/icons/ArrowRightIcon'>;
}
declare module 'material-ui-pickers/_shared/icons/DateRangeIcon.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/icons/DateRangeIcon'>;
}
declare module 'material-ui-pickers/_shared/icons/KeyboardIcon.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/icons/KeyboardIcon'>;
}
declare module 'material-ui-pickers/_shared/icons/TimeIcon.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/icons/TimeIcon'>;
}
declare module 'material-ui-pickers/_shared/MaskedInput.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/MaskedInput'>;
}
declare module 'material-ui-pickers/_shared/ModalDialog.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/ModalDialog'>;
}
declare module 'material-ui-pickers/_shared/PickerToolbar.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/PickerToolbar'>;
}
declare module 'material-ui-pickers/_shared/ToolbarButton.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/ToolbarButton'>;
}
declare module 'material-ui-pickers/_shared/WithUtils.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/WithUtils'>;
}
declare module 'material-ui-pickers/constants/ClockType.js' {
  declare module.exports: $Exports<'material-ui-pickers/constants/ClockType'>;
}
declare module 'material-ui-pickers/constants/DateTimePickerView.js' {
  declare module.exports: $Exports<'material-ui-pickers/constants/DateTimePickerView'>;
}
declare module 'material-ui-pickers/constants/dimensions.js' {
  declare module.exports: $Exports<'material-ui-pickers/constants/dimensions'>;
}
declare module 'material-ui-pickers/constants/prop-types.js' {
  declare module.exports: $Exports<'material-ui-pickers/constants/prop-types'>;
}
declare module 'material-ui-pickers/DatePicker/components/Calendar.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/components/Calendar'>;
}
declare module 'material-ui-pickers/DatePicker/components/CalendarHeader.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/components/CalendarHeader'>;
}
declare module 'material-ui-pickers/DatePicker/components/Day.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/components/Day'>;
}
declare module 'material-ui-pickers/DatePicker/components/DayWrapper.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/components/DayWrapper'>;
}
declare module 'material-ui-pickers/DatePicker/components/SlideTransition.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/components/SlideTransition'>;
}
declare module 'material-ui-pickers/DatePicker/components/Year.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/components/Year'>;
}
declare module 'material-ui-pickers/DatePicker/components/YearSelection.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/components/YearSelection'>;
}
declare module 'material-ui-pickers/DatePicker/DatePicker.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/DatePicker'>;
}
declare module 'material-ui-pickers/DatePicker/DatePickerInline.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/DatePickerInline'>;
}
declare module 'material-ui-pickers/DatePicker/DatePickerModal.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/DatePickerModal'>;
}
declare module 'material-ui-pickers/DatePicker/index.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/index'>;
}
declare module 'material-ui-pickers/DateTimePicker/components/DateTimePickerHeader.js' {
  declare module.exports: $Exports<'material-ui-pickers/DateTimePicker/components/DateTimePickerHeader'>;
}
declare module 'material-ui-pickers/DateTimePicker/components/DateTimePickerTabs.js' {
  declare module.exports: $Exports<'material-ui-pickers/DateTimePicker/components/DateTimePickerTabs'>;
}
declare module 'material-ui-pickers/DateTimePicker/components/DateTimePickerView.js' {
  declare module.exports: $Exports<'material-ui-pickers/DateTimePicker/components/DateTimePickerView'>;
}
declare module 'material-ui-pickers/DateTimePicker/DateTimePicker.js' {
  declare module.exports: $Exports<'material-ui-pickers/DateTimePicker/DateTimePicker'>;
}
declare module 'material-ui-pickers/DateTimePicker/DateTimePickerInline.js' {
  declare module.exports: $Exports<'material-ui-pickers/DateTimePicker/DateTimePickerInline'>;
}
declare module 'material-ui-pickers/DateTimePicker/DateTimePickerModal.js' {
  declare module.exports: $Exports<'material-ui-pickers/DateTimePicker/DateTimePickerModal'>;
}
declare module 'material-ui-pickers/DateTimePicker/index.js' {
  declare module.exports: $Exports<'material-ui-pickers/DateTimePicker/index'>;
}
declare module 'material-ui-pickers/dist/material-ui-pickers.cjs.js' {
  declare module.exports: $Exports<'material-ui-pickers/dist/material-ui-pickers.cjs'>;
}
declare module 'material-ui-pickers/dist/material-ui-pickers.esm.js' {
  declare module.exports: $Exports<'material-ui-pickers/dist/material-ui-pickers.esm'>;
}
declare module 'material-ui-pickers/dist/material-ui-pickers.umd.js' {
  declare module.exports: $Exports<'material-ui-pickers/dist/material-ui-pickers.umd'>;
}
declare module 'material-ui-pickers/dist/material-ui-pickers.umd.min.js' {
  declare module.exports: $Exports<'material-ui-pickers/dist/material-ui-pickers.umd.min'>;
}
declare module 'material-ui-pickers/index' {
  declare module.exports: $Exports<'material-ui-pickers'>;
}
declare module 'material-ui-pickers/index.js' {
  declare module.exports: $Exports<'material-ui-pickers'>;
}
declare module 'material-ui-pickers/MuiPickersUtilsProvider.js' {
  declare module.exports: $Exports<'material-ui-pickers/MuiPickersUtilsProvider'>;
}
declare module 'material-ui-pickers/TimePicker/components/Clock.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/components/Clock'>;
}
declare module 'material-ui-pickers/TimePicker/components/ClockNumber.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/components/ClockNumber'>;
}
declare module 'material-ui-pickers/TimePicker/components/ClockNumbers.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/components/ClockNumbers'>;
}
declare module 'material-ui-pickers/TimePicker/components/ClockPointer.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/components/ClockPointer'>;
}
declare module 'material-ui-pickers/TimePicker/components/TimePickerView.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/components/TimePickerView'>;
}
declare module 'material-ui-pickers/TimePicker/index.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/index'>;
}
declare module 'material-ui-pickers/TimePicker/TimePicker.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/TimePicker'>;
}
declare module 'material-ui-pickers/TimePicker/TimePickerInline.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/TimePickerInline'>;
}
declare module 'material-ui-pickers/TimePicker/TimePickerModal.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/TimePickerModal'>;
}
declare module 'material-ui-pickers/typings/date.js' {
  declare module.exports: $Exports<'material-ui-pickers/typings/date'>;
}
declare module 'material-ui-pickers/typings/extendMui.js' {
  declare module.exports: $Exports<'material-ui-pickers/typings/extendMui'>;
}
declare module 'material-ui-pickers/typings/overrides.js' {
  declare module.exports: $Exports<'material-ui-pickers/typings/overrides'>;
}
declare module 'material-ui-pickers/wrappers/ExtendWrapper.js' {
  declare module.exports: $Exports<'material-ui-pickers/wrappers/ExtendWrapper'>;
}
declare module 'material-ui-pickers/wrappers/InlineWrapper.js' {
  declare module.exports: $Exports<'material-ui-pickers/wrappers/InlineWrapper'>;
}
declare module 'material-ui-pickers/wrappers/ModalWrapper.js' {
  declare module.exports: $Exports<'material-ui-pickers/wrappers/ModalWrapper'>;
}
