// flow-typed signature: 433dd993d28507e4c7e510950a43177b
// flow-typed version: <<STUB>>/notistack_v^0.4.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'notistack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'notistack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'notistack/build/index' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarContext' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarItem/index' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarItem/SnackbarItem' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarItem/SnackbarItem.styles' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarItem/SnackbarItem.util' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarProvider' {
  declare module.exports: any;
}

declare module 'notistack/build/utils/constants' {
  declare module.exports: any;
}

declare module 'notistack/build/withSnackbar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'notistack/build/index.js' {
  declare module.exports: $Exports<'notistack/build/index'>;
}
declare module 'notistack/build/SnackbarContext.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarContext'>;
}
declare module 'notistack/build/SnackbarItem/index.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarItem/index'>;
}
declare module 'notistack/build/SnackbarItem/SnackbarItem.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarItem/SnackbarItem'>;
}
declare module 'notistack/build/SnackbarItem/SnackbarItem.styles.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarItem/SnackbarItem.styles'>;
}
declare module 'notistack/build/SnackbarItem/SnackbarItem.util.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarItem/SnackbarItem.util'>;
}
declare module 'notistack/build/SnackbarProvider.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarProvider'>;
}
declare module 'notistack/build/utils/constants.js' {
  declare module.exports: $Exports<'notistack/build/utils/constants'>;
}
declare module 'notistack/build/withSnackbar.js' {
  declare module.exports: $Exports<'notistack/build/withSnackbar'>;
}
