// flow-typed signature: b6617f12b868a4e5c08d3d6603e44fff
// flow-typed version: <<STUB>>/react-draft-wysiwyg_v^1.12.19/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-draft-wysiwyg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-draft-wysiwyg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-draft-wysiwyg/dist/react-draft-wysiwyg' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/components/Dropdown/Dropdown/__test__/dropdownTest' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/components/Dropdown/Dropdown/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/components/Dropdown/DropdownOption/__test__/dropdownOptionTest' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/components/Dropdown/DropdownOption/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/components/Dropdown/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/components/Option/__test__/optionTest' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/components/Option/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/components/Spinner/__test__/spinnerTest' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/components/Spinner/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/BlockType/__test__/blockControlTest' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/BlockType/Component/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/BlockType/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/ColorPicker/__test__/colorPickerTest' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/ColorPicker/Component/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/ColorPicker/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/Embedded/Component/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/Embedded/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/Emoji/Component/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/Emoji/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/FontFamily/__test__/fontFamilyControlTest' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/FontFamily/Component/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/FontFamily/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/FontSize/__test__/fontSizeControlTest' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/FontSize/Component/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/FontSize/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/History/__test__/historyControlTest' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/History/Component/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/History/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/Image/__test__/imageControlTest' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/Image/Component/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/Image/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/Inline/__test__/inlineControlTest' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/Inline/Component/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/Inline/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/Link/__test__/linkControlTest' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/Link/Component/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/Link/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/List/__test__/listControlsTest' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/List/Component/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/List/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/Remove/Component/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/Remove/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/TextAlign/__test__/textAlignControlTest' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/TextAlign/Component/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/controls/TextAlign/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/decorators/HashTag/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/decorators/Link/__test__/linkDecoratorTest' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/decorators/Link/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/decorators/Mention/addMention' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/decorators/Mention/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/decorators/Mention/Mention/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/decorators/Mention/Suggestion/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/Editor/__test__/editorTest' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/Editor/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/event-handler/focus' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/event-handler/keyDown' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/event-handler/modals' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/event-handler/suggestions' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/i18n/da' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/i18n/de' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/i18n/en' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/i18n/es' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/i18n/fr' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/i18n/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/i18n/it' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/i18n/ja' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/i18n/ko' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/i18n/nl' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/i18n/pl' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/i18n/pt' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/i18n/ru' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/i18n/zh_tw' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/i18n/zh' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/renderer/Embedded/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/renderer/Image/__test__/imageRendererTest' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/renderer/Image/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/renderer/index' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/utils/BlockStyle' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/utils/common' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/utils/handlePaste' {
  declare module.exports: any;
}

declare module 'react-draft-wysiwyg/src/utils/toolbar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-draft-wysiwyg/dist/react-draft-wysiwyg.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/dist/react-draft-wysiwyg'>;
}
declare module 'react-draft-wysiwyg/src/components/Dropdown/Dropdown/__test__/dropdownTest.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/components/Dropdown/Dropdown/__test__/dropdownTest'>;
}
declare module 'react-draft-wysiwyg/src/components/Dropdown/Dropdown/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/components/Dropdown/Dropdown/index'>;
}
declare module 'react-draft-wysiwyg/src/components/Dropdown/DropdownOption/__test__/dropdownOptionTest.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/components/Dropdown/DropdownOption/__test__/dropdownOptionTest'>;
}
declare module 'react-draft-wysiwyg/src/components/Dropdown/DropdownOption/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/components/Dropdown/DropdownOption/index'>;
}
declare module 'react-draft-wysiwyg/src/components/Dropdown/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/components/Dropdown/index'>;
}
declare module 'react-draft-wysiwyg/src/components/Option/__test__/optionTest.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/components/Option/__test__/optionTest'>;
}
declare module 'react-draft-wysiwyg/src/components/Option/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/components/Option/index'>;
}
declare module 'react-draft-wysiwyg/src/components/Spinner/__test__/spinnerTest.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/components/Spinner/__test__/spinnerTest'>;
}
declare module 'react-draft-wysiwyg/src/components/Spinner/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/components/Spinner/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/BlockType/__test__/blockControlTest.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/BlockType/__test__/blockControlTest'>;
}
declare module 'react-draft-wysiwyg/src/controls/BlockType/Component/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/BlockType/Component/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/BlockType/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/BlockType/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/ColorPicker/__test__/colorPickerTest.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/ColorPicker/__test__/colorPickerTest'>;
}
declare module 'react-draft-wysiwyg/src/controls/ColorPicker/Component/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/ColorPicker/Component/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/ColorPicker/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/ColorPicker/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/Embedded/Component/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/Embedded/Component/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/Embedded/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/Embedded/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/Emoji/Component/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/Emoji/Component/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/Emoji/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/Emoji/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/FontFamily/__test__/fontFamilyControlTest.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/FontFamily/__test__/fontFamilyControlTest'>;
}
declare module 'react-draft-wysiwyg/src/controls/FontFamily/Component/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/FontFamily/Component/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/FontFamily/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/FontFamily/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/FontSize/__test__/fontSizeControlTest.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/FontSize/__test__/fontSizeControlTest'>;
}
declare module 'react-draft-wysiwyg/src/controls/FontSize/Component/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/FontSize/Component/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/FontSize/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/FontSize/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/History/__test__/historyControlTest.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/History/__test__/historyControlTest'>;
}
declare module 'react-draft-wysiwyg/src/controls/History/Component/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/History/Component/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/History/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/History/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/Image/__test__/imageControlTest.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/Image/__test__/imageControlTest'>;
}
declare module 'react-draft-wysiwyg/src/controls/Image/Component/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/Image/Component/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/Image/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/Image/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/Inline/__test__/inlineControlTest.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/Inline/__test__/inlineControlTest'>;
}
declare module 'react-draft-wysiwyg/src/controls/Inline/Component/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/Inline/Component/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/Inline/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/Inline/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/Link/__test__/linkControlTest.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/Link/__test__/linkControlTest'>;
}
declare module 'react-draft-wysiwyg/src/controls/Link/Component/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/Link/Component/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/Link/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/Link/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/List/__test__/listControlsTest.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/List/__test__/listControlsTest'>;
}
declare module 'react-draft-wysiwyg/src/controls/List/Component/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/List/Component/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/List/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/List/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/Remove/Component/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/Remove/Component/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/Remove/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/Remove/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/TextAlign/__test__/textAlignControlTest.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/TextAlign/__test__/textAlignControlTest'>;
}
declare module 'react-draft-wysiwyg/src/controls/TextAlign/Component/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/TextAlign/Component/index'>;
}
declare module 'react-draft-wysiwyg/src/controls/TextAlign/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/controls/TextAlign/index'>;
}
declare module 'react-draft-wysiwyg/src/decorators/HashTag/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/decorators/HashTag/index'>;
}
declare module 'react-draft-wysiwyg/src/decorators/Link/__test__/linkDecoratorTest.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/decorators/Link/__test__/linkDecoratorTest'>;
}
declare module 'react-draft-wysiwyg/src/decorators/Link/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/decorators/Link/index'>;
}
declare module 'react-draft-wysiwyg/src/decorators/Mention/addMention.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/decorators/Mention/addMention'>;
}
declare module 'react-draft-wysiwyg/src/decorators/Mention/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/decorators/Mention/index'>;
}
declare module 'react-draft-wysiwyg/src/decorators/Mention/Mention/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/decorators/Mention/Mention/index'>;
}
declare module 'react-draft-wysiwyg/src/decorators/Mention/Suggestion/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/decorators/Mention/Suggestion/index'>;
}
declare module 'react-draft-wysiwyg/src/Editor/__test__/editorTest.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/Editor/__test__/editorTest'>;
}
declare module 'react-draft-wysiwyg/src/Editor/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/Editor/index'>;
}
declare module 'react-draft-wysiwyg/src/event-handler/focus.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/event-handler/focus'>;
}
declare module 'react-draft-wysiwyg/src/event-handler/keyDown.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/event-handler/keyDown'>;
}
declare module 'react-draft-wysiwyg/src/event-handler/modals.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/event-handler/modals'>;
}
declare module 'react-draft-wysiwyg/src/event-handler/suggestions.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/event-handler/suggestions'>;
}
declare module 'react-draft-wysiwyg/src/i18n/da.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/i18n/da'>;
}
declare module 'react-draft-wysiwyg/src/i18n/de.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/i18n/de'>;
}
declare module 'react-draft-wysiwyg/src/i18n/en.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/i18n/en'>;
}
declare module 'react-draft-wysiwyg/src/i18n/es.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/i18n/es'>;
}
declare module 'react-draft-wysiwyg/src/i18n/fr.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/i18n/fr'>;
}
declare module 'react-draft-wysiwyg/src/i18n/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/i18n/index'>;
}
declare module 'react-draft-wysiwyg/src/i18n/it.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/i18n/it'>;
}
declare module 'react-draft-wysiwyg/src/i18n/ja.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/i18n/ja'>;
}
declare module 'react-draft-wysiwyg/src/i18n/ko.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/i18n/ko'>;
}
declare module 'react-draft-wysiwyg/src/i18n/nl.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/i18n/nl'>;
}
declare module 'react-draft-wysiwyg/src/i18n/pl.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/i18n/pl'>;
}
declare module 'react-draft-wysiwyg/src/i18n/pt.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/i18n/pt'>;
}
declare module 'react-draft-wysiwyg/src/i18n/ru.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/i18n/ru'>;
}
declare module 'react-draft-wysiwyg/src/i18n/zh_tw.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/i18n/zh_tw'>;
}
declare module 'react-draft-wysiwyg/src/i18n/zh.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/i18n/zh'>;
}
declare module 'react-draft-wysiwyg/src/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/index'>;
}
declare module 'react-draft-wysiwyg/src/renderer/Embedded/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/renderer/Embedded/index'>;
}
declare module 'react-draft-wysiwyg/src/renderer/Image/__test__/imageRendererTest.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/renderer/Image/__test__/imageRendererTest'>;
}
declare module 'react-draft-wysiwyg/src/renderer/Image/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/renderer/Image/index'>;
}
declare module 'react-draft-wysiwyg/src/renderer/index.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/renderer/index'>;
}
declare module 'react-draft-wysiwyg/src/utils/BlockStyle.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/utils/BlockStyle'>;
}
declare module 'react-draft-wysiwyg/src/utils/common.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/utils/common'>;
}
declare module 'react-draft-wysiwyg/src/utils/handlePaste.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/utils/handlePaste'>;
}
declare module 'react-draft-wysiwyg/src/utils/toolbar.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/src/utils/toolbar'>;
}
